apiVersion: apps/v1
kind: Deployment
metadata:
  name: jr-movement-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jr-movement-api
  template:
    metadata:
      labels:
        app: jr-movement-api
    spec:
      volumes:
      - name: jr-movement-api-persistent-storage
        persistentVolumeClaim:
          claimName: jr-movement-api-pv-claim
      containers:
        - name: jr-movement-api
          image: 'appademin/jr-movement-api:0.3.0'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          volumeMounts:
          - mountPath: /pb/pb_data
            name: jr-movement-api-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: jr-movement-api-service
spec:
  selector:
    app: jr-movement-api
  ports:
    - protocol: TCP
      port: 8080